"""posts table

Revision ID: 4031131179ef
Revises: 9a0959f666bd
Create Date: 2021-10-31 12:31:05.379966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4031131179ef'
down_revision = '9a0959f666bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Post', type_='foreignkey')
    op.drop_column('Post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'Post', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###
